import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export async function POST(request: NextRequest) {
  try {
    console.log('🧪 Testing simple DALL-E generation...')

    // Check if OpenAI API key is configured
    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json(
        { error: 'OpenAI API key not configured' },
        { status: 500 }
      )
    }

    // Simple test prompt
    const testPrompt = "A beautiful modern bedroom with white bedding, professional product photography, clean and minimal, high quality, studio lighting"

    console.log('🎨 Generating test image with DALL-E 3...')

    // Generate image
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt: testPrompt,
      n: 1,
      size: "1024x1024",
      quality: "hd",
      response_format: "url"
    })

    const generatedImageUrl = response.data[0]?.url

    if (!generatedImageUrl) {
      throw new Error('No image generated by OpenAI')
    }

    console.log('✅ Simple test successful!')

    return NextResponse.json({
      success: true,
      imageUrl: generatedImageUrl,
      prompt: testPrompt
    })

  } catch (error: any) {
    console.error('❌ Simple test error:', error)
    
    return NextResponse.json(
      { 
        error: 'Simple test failed',
        details: error.message || 'Unknown error',
        code: error.code || 'unknown'
      },
      { status: 500 }
    )
  }
} 